version: '3'
services:
  angular-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:4200"
    container_name: angular-ui-admin
    volumes:
       - "/app/node_modules"
       - ".:/app"